SEED = 12345678901234567890123456789012

[kernels]
NEIGHBOR_KERNEL = [[[1, 1, 1],[1, 0, 1],[1, 1, 1]]]
KERNEL_1 = [31, 31]
KERNEL_2 = [15, 15]
KERNEL_3 = [15, 15]
KERNEL_4 = [31, 31]
KERNEL_5 = [3, 3]

[params]
TILES = 20
GRID_SIZE = 64
SEEDS_PER_TILE = 5
UPDATE_ITERATIONS = 25
NEIGHBOR_ACTIVATION_FACTOR = 0.11
THRESHOLD = -0.55
MULTIPLIERS = [2, 4, 8, 16, 32]
AMPLITUDE = 48
WEIGHTS = [0.50, 0.25, 0.09, 0.08, 0.08]
RESIZE = 512
CONTRAST_FACTOR = 3.0
BLEND_PERCENT = 0.85
SAVE = true
